name: build
on: push
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'json'
    - run: |
        readarray -t files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.all }}')"
        # Escape newlines (replace \n with %0A)
        echo $files
        echo "::set-output name=matrix::$( echo "${files}" | sed ':a;N;$!ba;s/\n/%0A/g' )"
        echo ${{ steps.set-matrix.outputs.matrix }}
  deploy:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.component }}
