name: pr_checks
on:
  pull_request:
    branches:
      - main

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check commit is in beta
        run: |
          success=0
          git fetch origin beta
          git fetch origin main

          # get a list of commits that from pull reuqest
          arr=()
          while read -r line; do
            arr+=("$line")
          done < <(git log --pretty=format:"%H"  HEAD...origin/main)

          # check for the commits that are not in beta
          for commit in "${arr[@]}"; do
            if git merge-base --is-ancestor $commit origin/beta; then
              echo "beta branch contains $commit"
            else
              echo "beta branch does not contain $commit"
              success=1
            fi
          done

          exit $success
