name: pr_checks
on:
  pull_request:
    branches:
      - main

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check ${{GITHUB_SHA}} is in beta
        run: |
          git fetch origin beta
          if git merge-base --is-ancestor $GITHUB_SHA beta; then
            echo "beta branch does not contain $GITHUB_SHA"
            exit 1
          else
            echo "beta branch contains $GITHUB_SHA"
          fi
