name: pr_checks
on:
  pull_request:
    branches:
      - main
on:
  push:
    branches:
      - main

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check that beta can be merged in main
        run: |
          git fetch origin beta
          git merge --no-commit --no-ff beta
