name: workflow1

on:
  push:
    branches:
    - 'main'

jobs:
  call-workflow-passing-data:
    uses: gimmyxd/test-gh/.github/workflows/reusable-workflow.yml@${{github.ref}}
    with:
      username: workflow1
